### ISSUE TITLE
librechat-rag-api CreateContainerConfigError

### ISSUE THREAD

**Issue by kaykhan** [bat-bs/helm-charts#61]
When enabling librechat-reg-api we get a CreateContainerConfigError because librechat-vectordb secret is not found. What is this secret support to contain? 

```
    librechat-rag-api:
      enabled: true
```

**Comment by eeedean** [comment]
As described in [the template](https://github.com/bat-bs/helm-charts/blob/f4e4d681106eafc73a1b384049d90fa762bdf39a/charts/librechat-rag-api/templates/vectordb-secret.yaml):
```yaml
{{ if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: librechat-vectordb
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  replication-password: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
```

Usually, it should be generated automatically with random contents, as you can see. However, you can of course create it manually beforehand.
