### ISSUE TITLE
MultiLine Value for librechat.configYamlContent Inserts Pipe Character Into ConfigMap

### ISSUE THREAD

**Issue by allenmercer** [bat-bs/helm-charts#67]
When modifying the values.yaml for librechat with the following:
values.yaml
```
librechat:
  configYamlContent: |
    version: 1.0.3
    endpoints:
      custom:
        - name: "MyCustomEndpoint"
          apiKey: "MyKey"
          baseURL: "http://x.x.x.x:x/v1/"
          models:
            default: ["MyModel"]
            fetch: false
            userIdQuery: false
          titleConvo: true
          titleMethod: "completion"
          titleModel: "current_model"
          summarize: false
          summaryModel: "current_model"
          forcePrompt: false
          modelDisplayLabel: "MyCustomEndpoint"
```

And then getting the ConfigMap with kubectl get -n test configmaps test-librechat-config -o yaml.
The ConfigMap retains the PipeCharacter.

kubectl get -n test configmaps test-librechat-config -o yaml
```
apiVersion: v1
data:
  librechat.yaml: |
    |
      version: 1.0.3
      endpoints:
      custom:
      .........
```

I believe that the charts/librechat/templates/configmap.yaml need the following change:
From:
```
{{- if .Values.librechat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librechat.fullname" $ }}-config
data:
  librechat.yaml: |
    {{ .Values.librechat.configYamlContent | toYaml | indent 4 }}

{{- end }}
```

To:
```
{{- if .Values.librechat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librechat.fullname" $ }}-config
data:
  librechat.yaml: {{ .Values.librechat.configYamlContent | toYaml | indent 4 }}
{{- end }}
```

I tested locally and this fixes the problem.
I can submit a PR for this if you like.

**Comment by allenmercer** [comment]
Helm: version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"dirty", GoVersion:"go1.23.4"}
LibreChat Chart Version: 1.0.0

If I remove the Pipe like so:
```
librechat:
  configYamlContent:
    version: 1.0.3
    endpoints:
      custom:
        - name: "MyCustomEndpoint"
          apiKey: "MyKey"
          baseURL: "http://x.x.x.x:x/v1/"
          .........
```
I get the following error with when running helm upgrade:
coalesce.go:289: warning: destination for librechat.librechat.configYamlContent is a table. Ignoring non-table value ()
coalesce.go:289: warning: destination for librechat.librechat.configYamlContent is a table. Ignoring non-table value ()

But the config map looks good.

Could you show me a an example of your yaml file confYamlContents?
